'use client';

import { useState } from 'react';
import { FileText, Loader2, AlertCircle, CheckCircle, Copy, Check } from 'lucide-react';
import { analyzeAIContent } from '@/lib/api';
import LoadingSpinner from './LoadingSpinner';

interface AnalysisResult {
  ai_probability: number;
  likelihood: string;
  message: string;
  metrics: {
    pattern_score: number;
    structure_score: number;
    vocabulary_score: number;
    consistency_score: number;
  };
  indicators: string[];
  statistics: {
    word_count: number;
    sentence_count: number;
    avg_sentence_length: number;
    unique_word_ratio: number;
  };
}

export default function AIContentDetector() {
  const [text, setText] = useState('');
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [result, setResult] = useState<AnalysisResult | null>(null);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  const handleAnalyze = async () => {
    if (!text.trim()) {
      setError('Please enter some text to analyze');
      return;
    }

    if (text.length < 50) {
      setError('Text must be at least 50 characters long');
      return;
    }

    setIsAnalyzing(true);
    setError('');
    setResult(null);

    try {
      const response = await analyzeAIContent(text);
      if (response.success) {
        setResult(response.data);
      } else {
        setError(response.error || 'Analysis failed');
      }
    } catch (err: any) {
      setError(err.message || 'Failed to analyze text');
    } finally {
      setIsAnalyzing(false);
    }
  };

  const handleCopy = () => {
    if (result) {
      const summary = `AI Detection Analysis:
AI Probability: ${result.ai_probability}%
Likelihood: ${result.likelihood}
${result.message}

Indicators:
${result.indicators.map((i) => `• ${i}`).join('\n')}

Statistics:
• Word Count: ${result.statistics.word_count}
• Sentence Count: ${result.statistics.sentence_count}
• Avg Sentence Length: ${result.statistics.avg_sentence_length} words
• Unique Word Ratio: ${result.statistics.unique_word_ratio}`;
      
      navigator.clipboard.writeText(summary);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const getLikelihoodColor = (likelihood: string) => {
    switch (likelihood) {
      case 'High':
        return 'text-red-600 bg-red-50 border-red-200';
      case 'Medium':
        return 'text-orange-600 bg-orange-50 border-orange-200';
      case 'Low':
        return 'text-yellow-600 bg-yellow-50 border-yellow-200';
      default:
        return 'text-green-600 bg-green-50 border-green-200';
    }
  };

  const getProgressBarColor = (probability: number) => {
    if (probability >= 70) return 'bg-red-500';
    if (probability >= 50) return 'bg-orange-500';
    if (probability >= 30) return 'bg-yellow-500';
    return 'bg-green-500';
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Header */}
      <div className="text-center space-y-2">
        <div className="flex items-center justify-center gap-2">
          <FileText className="w-8 h-8 text-blue-600" />
          <h2 className="text-3xl font-bold text-gray-900">AI Content Detector</h2>
        </div>
        <p className="text-gray-600">Analyze text to detect if it was generated by AI models</p>
      </div>

      {/* Text Input Area */}
      <div className="bg-white rounded-lg shadow-md p-6 space-y-4">
        <div>
          <label htmlFor="text-input" className="block text-sm font-medium text-gray-700 mb-2">
            Enter Text to Analyze (minimum 50 characters)
          </label>
          <textarea
            id="text-input"
            value={text}
            onChange={(e) => setText(e.target.value)}
            placeholder="Paste or type the text you want to analyze for AI-generated content..."
            className="w-full h-48 px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent resize-none"
            disabled={isAnalyzing}
          />
          <div className="flex justify-between items-center mt-2">
            <p className="text-sm text-gray-500">
              {text.length} characters {text.length >= 50 ? '✓' : `(need ${50 - text.length} more)`}
            </p>
            {text && (
              <button
                onClick={() => setText('')}
                className="text-sm text-gray-500 hover:text-gray-700"
              >
                Clear
              </button>
            )}
          </div>
        </div>

        <button
          onClick={handleAnalyze}
          disabled={isAnalyzing || text.length < 50}
          className="w-full bg-blue-600 text-white py-3 px-6 rounded-lg font-medium hover:bg-blue-700 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors flex items-center justify-center gap-2"
        >
          {isAnalyzing ? (
            <>
              <Loader2 className="w-5 h-5 animate-spin" />
              Analyzing...
            </>
          ) : (
            <>
              <FileText className="w-5 h-5" />
              Analyze Text
            </>
          )}
        </button>
      </div>

      {/* Error Message */}
      {error && (
        <div className="bg-red-50 border border-red-200 rounded-lg p-4 flex items-start gap-3">
          <AlertCircle className="w-5 h-5 text-red-600 flex-shrink-0 mt-0.5" />
          <p className="text-red-800">{error}</p>
        </div>
      )}

      {/* Analysis Results */}
      {result && (
        <div className="bg-white rounded-lg shadow-md p-6 space-y-6">
          {/* Header with Copy Button */}
          <div className="flex items-center justify-between">
            <h3 className="text-xl font-semibold text-gray-900">Analysis Results</h3>
            <button
              onClick={handleCopy}
              className="flex items-center gap-2 px-3 py-2 text-sm text-gray-600 hover:text-gray-900 hover:bg-gray-100 rounded-lg transition-colors"
            >
              {copied ? (
                <>
                  <Check className="w-4 h-4 text-green-600" />
                  Copied!
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4" />
                  Copy Results
                </>
              )}
            </button>
          </div>

          {/* AI Probability Score */}
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-sm font-medium text-gray-700">AI Probability</span>
              <span className="text-2xl font-bold text-gray-900">{result.ai_probability}%</span>
            </div>
            <div className="w-full bg-gray-200 rounded-full h-4 overflow-hidden">
              <div
                className={`h-full ${getProgressBarColor(result.ai_probability)} transition-all duration-500`}
                style={{ width: `${result.ai_probability}%` }}
              ></div>
            </div>
            <div
              className={`inline-flex items-center gap-2 px-4 py-2 rounded-lg border ${getLikelihoodColor(result.likelihood)}`}
            >
              {result.likelihood === 'High' || result.likelihood === 'Medium' ? (
                <AlertCircle className="w-5 h-5" />
              ) : (
                <CheckCircle className="w-5 h-5" />
              )}
              <span className="font-medium">{result.likelihood} Likelihood</span>
            </div>
            <p className="text-gray-600 italic">{result.message}</p>
          </div>

          {/* Detailed Metrics */}
          <div>
            <h4 className="text-lg font-semibold text-gray-900 mb-3">Detailed Metrics</h4>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {Object.entries(result.metrics).map(([key, value]) => (
                <div key={key} className="bg-gray-50 rounded-lg p-4">
                  <div className="flex justify-between items-center mb-2">
                    <span className="text-sm font-medium text-gray-600 capitalize">
                      {key.replace('_', ' ')}
                    </span>
                    <span className="text-lg font-semibold text-gray-900">{value}%</span>
                  </div>
                  <div className="w-full bg-gray-200 rounded-full h-2 overflow-hidden">
                    <div
                      className="h-full bg-blue-500 transition-all duration-500"
                      style={{ width: `${value}%` }}
                    ></div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Indicators */}
          <div>
            <h4 className="text-lg font-semibold text-gray-900 mb-3">Detection Indicators</h4>
            <ul className="space-y-2">
              {result.indicators.map((indicator, index) => (
                <li key={index} className="flex items-start gap-2">
                  <span className="text-blue-600 mt-1">•</span>
                  <span className="text-gray-700">{indicator}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Text Statistics */}
          <div>
            <h4 className="text-lg font-semibold text-gray-900 mb-3">Text Statistics</h4>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <div className="bg-gray-50 rounded-lg p-4 text-center">
                <p className="text-2xl font-bold text-gray-900">{result.statistics.word_count}</p>
                <p className="text-sm text-gray-600">Words</p>
              </div>
              <div className="bg-gray-50 rounded-lg p-4 text-center">
                <p className="text-2xl font-bold text-gray-900">{result.statistics.sentence_count}</p>
                <p className="text-sm text-gray-600">Sentences</p>
              </div>
              <div className="bg-gray-50 rounded-lg p-4 text-center">
                <p className="text-2xl font-bold text-gray-900">{result.statistics.avg_sentence_length}</p>
                <p className="text-sm text-gray-600">Avg Length</p>
              </div>
              <div className="bg-gray-50 rounded-lg p-4 text-center">
                <p className="text-2xl font-bold text-gray-900">{result.statistics.unique_word_ratio}</p>
                <p className="text-sm text-gray-600">Uniqueness</p>
              </div>
            </div>
          </div>

          {/* Disclaimer */}
          <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
            <p className="text-sm text-yellow-800">
              <strong>Disclaimer:</strong> This analysis uses heuristic methods and pattern matching. 
              Results should be used as a guideline, not definitive proof. False positives and negatives can occur.
            </p>
          </div>
        </div>
      )}
    </div>
  );
}
