from fastapi import APIRouter, Form, HTTPException
from app.services.ai_detection import ai_detection_service

router = APIRouter()


@router.post("/analyze")
async def analyze_text(
    text: str = Form(..., description="Text to analyze for AI-generated content")
):
    """
    Analyze text to detect if it was generated by AI
    
    Returns probability score and detailed metrics
    
    Minimum text length: 50 characters
    """
    try:
        result = ai_detection_service.analyze_text(text)
        
        if not result.get("success"):
            raise HTTPException(
                status_code=400,
                detail=result.get("error", "Analysis failed")
            )
        
        return {
            "success": True,
            "message": "Analysis completed successfully",
            "data": result
        }
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Error analyzing text: {str(e)}"
        )


@router.get("/info")
async def get_detection_info():
    """
    Get information about the AI detection service
    """
    return {
        "success": True,
        "info": {
            "name": "AI Content Detection",
            "version": "1.0.0",
            "description": "Analyzes text to detect AI-generated content using heuristic analysis",
            "metrics": [
                "Pattern matching for AI-specific phrases",
                "Structural consistency analysis",
                "Vocabulary sophistication scoring",
                "Grammar and punctuation consistency"
            ],
            "minimum_text_length": 50,
            "output": {
                "ai_probability": "Percentage likelihood (0-100)",
                "likelihood": "High, Medium, Low, or Very Low",
                "metrics": "Individual scores for each analysis method",
                "indicators": "Specific AI characteristics found",
                "statistics": "Text statistics (word count, sentence length, etc.)"
            }
        }
    }
